spring.application.name=urlShortener

spring.config.import=aws-secretsmanager:db_secret?prefix=db.

spring.datasource.url=jdbc:postgresql://${db.host}:${db.port}/postgres
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.cloud.aws.region.static=us-east-1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect